import os

# Project name
PROJECT_NAME = 'MyProject'

# Directories
_DIRECTORY_DATA = './data'
DIRECTORY_IMAGES = os.path.join(_DIRECTORY_DATA, PROJECT_NAME, 'google_images')
DIRECTORY_PREDICTIONS = os.path.join(_DIRECTORY_DATA, PROJECT_NAME, 'prediction_images')
DIRECTORY_SHAPEFILES = os.path.join(_DIRECTORY_DATA, PROJECT_NAME, 'shapefiles')

# Coordinates Samples File
COORDINATES_FILE = os.path.join(DIRECTORY_SHAPEFILES, 'coordinates.shp')
COORDINATES_CRS_PROJECTION = 'epsg:6372'
COORDINATES_CRS_LATLONG = 'epsg:4326'

# Image spatial parameters
IMAGE_HEIGHT = 552
IMAGE_WIDTH = 552
IMAGE_CHANNELS = 3
IMAGE_RESOLUTION_X = 0.5635245901639344
IMAGE_RESOLUTION_Y = 0.5635245901639344
IMAGE_CROP_SIZE = 20
IMAGE_DTHR = 250

# Neural Network
IMAGE_FIXED_HEIGHT = IMAGE_HEIGHT - IMAGE_CROP_SIZE * 2
IMAGE_FIXED_WIDTH = IMAGE_WIDTH - IMAGE_CROP_SIZE * 2
NN_INPUT_SHAPE = (
    IMAGE_FIXED_HEIGHT,
    IMAGE_FIXED_WIDTH,
    IMAGE_CHANNELS
)
NN_CLASSES = 2
NN_WEIGHTS_ID = '20181123_202857'
NN_WEIGHTS_FILE = f'./neural_network/Model/weights_{NN_WEIGHTS_ID}.h5'

# Polygons Extraction
PREDICTION_THR = 0.95
PREDICTION_PAD_SIZE = 20
PREDICTION_FIND_COUNTOURS = 0.8
PREDICTION_RELATION_FILE = COORDINATES_FILE.replace('.shp', '_predictions.shp')
POLYGONS_OUTPUT_FILE = os.path.join(DIRECTORY_SHAPEFILES, 'Polyons_<NOW(%Y%m%d_%H%M%S)>_weights_<NN_WEIGHTS_ID>.shp')

# Image filename rules 
IMAGE_EXT = '.png'
IMAGE_FMT_DATE = '%Y%m%d'
IMAGE_FMT_TIMESTAMP = '%Y%m%d_%H%M%S_%f'
IMAGE_PARTITION = 'date'
IMAGE_PREFIX = 'Image'
IMAGE_SUFFIX_DATA = '_data.png'
IMAGE_SUFFIX_PREDICTION = f'_weights_{NN_WEIGHTS_ID}_prediction.png'
